name: tests

on:
  push:
    branches: [dev, main]
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with black
        run: |
          black . --check --preview
      - name: Lint with pylint
        run: |
          pylint src tests --disable=fixme
      - name: Check typing with mypy
        run: |
          mypy . --check-untyped-defs
      - name: Test with testslide
        run: |
          find tests -type f -name "test_*.py" | xargs testslide
